### PR TITLE
Added dashu crate, introduced new versions

### PR DESCRIPTION
**Pull request by amamic1803**
Hi,
I added dashu crate to this benchmark. I also changed all crates to their latest versions. As I changed clap to the newest version, I also had to rewrite the code that deals with argument parsing, but I think I managed to replicate exact behaviour as before. I removed any mention of the old crates, not benhcmarked anymore (rust-gmp). I was also reading the part of the code that deals with benchmarking and I changed it a little. I think I made good simplifications that work pretty good. I'm getting the same results as you listed in the README on my laptop so I think that my benchmarking strategy works well while being much easier to understand and follow. What I did is I made each library do at least 5 iterations of the test, or run at least 60 seconds. Whichever is longer. I don't think it is neccessary to completely separate benchmarking samples as you did because we are only really interested in the fastest run anyway. I changed the output a little to appear prettier. README is also edited to account for these changes, I only didn't touch the timings table, you will have to measure that on your hardware and fill it. I did create a workflow that builds binary and runs benchmarks on push/pull_request/workflow_dispatch, but I don't know if its' benchmarks can be trusted since I believe that processing power available to jobs varies depending on the load on the GitHub servers. I tried turning on static linking c runtime cargo option, but dashu crate wouldn't compile for some reason, so I gave up on that.
I hope you will accept my changes. I know that they are pretty big, especially those around benchmark function so I will understand if you choose not to.
Regards

### CODE REVIEW

**Comment by amamic1803** [comment]
I added workflow jobs that run on macOS and Windows. Sorry for so much unneeded commits, it is tough to get workflow right and since I can't test it locally, each modification requires a new commit... 😢. Again, I don't think results from GitHub Actions are accurate, you should run benchmark yourself.

**Comment by tczajka** [comment]
Thanks for making these changes. There are many things here in addition to just adding a new library and upgrading versions, so it would be easier to review those separately. But I'll take this anyway.

BUT: I don't think the new benchmarking strategy is better. This seems like a deterioration -- for very short running tasks you want to time multiple runs, rather than timing each run separately. Taking the minimum time of all the individual short runs creates the risk of bad clock resolution or other random factors affecting the result.

Can you revert this part? If you think this makes sense, open a separate ticket.

**Comment by amamic1803** [comment]
Hi, thanks for reviewing my changes. You are right, I assumed that clocks are precise enough, but after reading a bit I agree that it might not always be the case. I will revert this change, but I think that all iteration work should be done by one function instead of sending number of iterations as an argument to run_task function. You probably did it this way to decrease the number of function calls which also take time. I will add #inline(always) attribute to those functions instead so that they get inlined and the cost of calling them doesn't appear anymore. Of course that match block inside run_task will still need to be run every iteration, but I don't think that it can make much difference to results, it should be pretty cheap, after all, it is only one match block. Expect a fix in a few days, currently I'm having some performance problems with my IDE, I'm waiting for jetbrains support to fix a problem.

**Comment by tczajka** [comment]
I don't understand why you want to implement any additional changes on this pull request. What you're suggesting is completely unrelated to this pull request. I'll say please don't change the benchmarking loop in this PR.

If you want to change the benchmarking loop for some reason, let's leave it to a separate pull request. But I don't see the point of moving the extra match statement inside the loop. It's redundant to redo the match statement each time, so that sounds counterproductive (not just for performance, but also for code clarity). If anything, I'd actually go the other way and extract the other `match` from inside the loop body.

**Comment by tczajka** [comment]
There are still a bunch of changes to the benchmarking code that I don't understand the reason for.

Sorry I can't take it like this.

The name of the PR mentions adding a new crate and updating versions. Whereas there seem to be at least the following changes here:
* add a new crate
* update versions
* delete some crates
* github actions workflows
* Rust edition update
* semver version change (why? don't do that,)
* clap version upgrade with the corresponding rewrite
* README formatting
* output formatting
* benchmarking code changes (not sure what changed)

I suggest closing this PR and doing these things one change at a time, without changing other unrelated things at the same time.

**Pull request closed without merging**
